baseurl = "https://samuelmartingc.github.io/blog/"
languageCode = "en"
title = "ItAndWhatever"
author = "Samuel Martin"
copyright = "Copyright (c) 2016 - 2036, Samuel Martin; all rights reserved."
canonifyurls = true
paginate = 5
theme = "hugo_theme_beg"
[params]
  disqusShortname = "samuelmartingc-blog" # optional
  toc = true # optional, When set to TRUE this parameter, table of contents appears in all articles.
# currently using hugo_theme_beg
